### ISSUE TITLE
about jenkins grafana template

### ISSUE THREAD

**Issue by zeyangli** [nthienan/demo-credstash#1]
Hello, my name is Zeyang. I saw the template you shared on grafana's official website. Are there any documents used? thank you very much. Interested in this template you shared. Thank you, please help me.

Since I can't find your contact information, I can only contact you here. very sorry

**Comment by zeyangli** [comment]
https://grafana.com/grafana/dashboards/10557/reviews

**Comment by nthienan** [comment]
Give me your email address.

**Comment by zeyangli** [comment]
my email address:  610556220@qq.com
